version: "3"
services:
  redis:
    image: redis:alpine
    container_name: database
    ports:
      - "6379:6379"

  app:
    build: .
    container_name: rate_limiter
    ports:
      - "8080:8080"
    env_file:
      - .env
    depends_on:
      - redis